int quisuisje();
int permute();
int year();
int division();
int multi_aux(int a, int b);
int multi();
int pyramide();
int factoriel();
int sum();
int longue_cons();
int nombre_parfait();
int fibonacci();
int tableau();
int tableau_paire();
int random();
int randint(int min, int max);
int tab_rand();